import * as THREE from './vendor/three.module.js';

const lerp=(a,b,t)=>a+(b-a)*t;
const clamp01=v=>Math.max(0,Math.min(1,Number.isFinite(v)?v:0));
function css(v){return `#${new THREE.Color(v).getHexString()}`}
function cloth(color,kind){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle=css(color);x.fillRect(0,0,128,128);const g=x.createLinearGradient(0,0,128,0);g.addColorStop(0,'rgba(20,14,10,.2)');g.addColorStop(.3,'rgba(255,245,220,.08)');g.addColorStop(1,'rgba(20,14,10,.22)');x.fillStyle=g;x.fillRect(0,0,128,128);x.strokeStyle='rgba(25,18,13,.16)';x.lineWidth=2;x.beginPath();x.moveTo(64,0);x.lineTo(64,128);x.stroke();if(kind==='shirt'){x.beginPath();x.moveTo(20,93);x.quadraticCurveTo(64,104,108,93);x.stroke()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.minFilter=THREE.LinearFilter;return t}
function mat(color,map=null,shininess=7){return new THREE.MeshPhongMaterial({color,map,shininess,flatShading:false})}
function add(p,g,m,pos=[0,0,0]){const o=new THREE.Mesh(g,m);o.position.set(...pos);o.castShadow=true;p.add(o);return o}
function segment(length,a,b,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(b,a,length,12,3),m);o.position.y=-length/2;o.castShadow=true;return o}
function arm(body,side,m){const upper=new THREE.Group();upper.position.set(side*.31,1.76,0);upper.rotation.z=side*-.08;body.add(upper);upper.add(segment(.43,.082,.072,m.shirt));const fore=new THREE.Group();fore.position.y=-.405;upper.add(fore);fore.add(segment(.38,.07,.058,m.skin));const hand=add(fore,new THREE.SphereGeometry(.075,12,9),m.skin,[0,-.4,.015]);hand.scale.set(.88,1.25,.72);const thumb=add(fore,new THREE.SphereGeometry(.03,9,7),m.skin,[side*.062,-.375,.04]);thumb.scale.set(1.2,.72,.7);thumb.rotation.z=side*-.55;return{upper,fore,hand}}
function leg(body,side,m){const upper=new THREE.Group();upper.position.set(side*.135,1.02,0);body.add(upper);upper.add(segment(.48,.112,.092,m.trousers));const lower=new THREE.Group();lower.position.y=-.455;upper.add(lower);lower.add(segment(.43,.09,.068,m.trousers));const ankle=add(lower,new THREE.CylinderGeometry(.061,.067,.09,10),m.skin,[0,-.445,0]);const shoe=add(lower,new THREE.SphereGeometry(.12,14,9),m.shoe,[0,-.505,.075]);shoe.scale.set(.82,.5,1.5);return{upper,lower,shoe,ankle}}
function hair(head,m,style){const crown=add(head,new THREE.SphereGeometry(.215,16,11),m.hair,[0,.075,-.005]);crown.scale.set(1.04,.88,1.03);for(let i=0;i<5;i++){const q=add(head,new THREE.SphereGeometry(.05,10,7),m.hair,[lerp(-.13,.13,i/4),.1-Math.abs(i-2)*.015,.165]);q.scale.set(1.15,.72,.55)}if(style==='bob'||style==='long')for(const side of[-1,1]){const q=add(head,new THREE.SphereGeometry(.105,12,9),m.hair,[side*.17,-.04,-.015]);q.scale.set(.72,style==='long'?1.85:1.35,.9)}}
export function createHuman(colors={}){const st=cloth(colors.shirt??0x6b8060,'shirt'),tt=cloth(colors.trousers??0x39485a,'trousers');const m={skin:mat(colors.skin??0xb97d58,null,11),hair:mat(colors.hair??0x3a241a),shirt:mat(0xffffff,st,4),trousers:mat(0xffffff,tt,3),shoe:mat(colors.shoe??0x2b211d,null,18),eye:mat(0x241b16),white:mat(0xe8dfcf)};const root=new THREE.Group(),body=new THREE.Group();root.add(body);const pelvis=add(body,new THREE.CylinderGeometry(.22,.255,.25,14,2),m.trousers,[0,1.08,0]);pelvis.scale.z=.72;const torso=add(body,new THREE.SphereGeometry(.34,16,12),m.shirt,[0,1.48,0]);torso.scale.set(.86,1.05,.62);const waist=add(body,new THREE.TorusGeometry(.215,.027,7,16),m.trousers,[0,1.16,0]);waist.rotation.x=Math.PI/2;waist.scale.y=.72;add(body,new THREE.CylinderGeometry(.072,.083,.14,12),m.skin,[0,1.88,0]);const head=new THREE.Group();head.position.set(0,2.12,0);body.add(head);const cranium=add(head,new THREE.SphereGeometry(.205,18,13),m.skin);cranium.scale.set(.88,1.08,.88);const jaw=add(head,new THREE.SphereGeometry(.145,16,11),m.skin,[0,-.13,.02]);jaw.scale.set(.87,.72,.88);for(const side of[-1,1])add(head,new THREE.SphereGeometry(.014,8,6),m.eye,[side*.06,.02,.2]);const nose=add(head,new THREE.ConeGeometry(.027,.075,9),m.skin,[0,-.025,.205]);nose.rotation.x=Math.PI/2;hair(head,m,colors.hairStyle||'short');const leftArm=arm(body,-1,m),rightArm=arm(body,1,m),leftLeg=leg(body,-1,m),rightLeg=leg(body,1,m);return{root,body,head,leftArm,rightArm,leftLeg,rightLeg,materials:m,textures:[st,tt]}}
function poseLeg(l,p,w){const s=((p%1)+1)%1,stance=s<.62,q=stance?s/.62:(s-.62)/.38,z=(stance?lerp(.22,-.22,q):lerp(-.22,.22,q*q*(3-2*q)))*w,lift=stance?0:Math.sin(q*Math.PI)*.105*w,y=-.88+lift,a=.455,b=.425,d=Math.min(a+b-.002,Math.max(.15,Math.hypot(z,y))),k=Math.acos(Math.max(-1,Math.min(1,(d*d-a*a-b*b)/(2*a*b)))),target=Math.atan2(z,-y),hip=-target+Math.atan2(b*Math.sin(k),a+b*Math.cos(k));l.upper.rotation.x=hip;l.lower.rotation.x=-k;l.shoe.rotation.x=-(hip-k)}
export function poseHumanWalk(h,p,weight=1){const w=clamp01(weight);poseLeg(h.leftLeg,p,w);poseLeg(h.rightLeg,p+.5,w);const s=Math.sin(p*Math.PI*2)*w;h.leftArm.upper.rotation.x=-s*.42;h.rightArm.upper.rotation.x=s*.42;h.leftArm.fore.rotation.x=-.08-Math.max(0,s)*.12;h.rightArm.fore.rotation.x=-.08-Math.max(0,-s)*.12;h.body.position.y=Math.abs(Math.sin(p*Math.PI*2))*.025*w;h.body.rotation.z=Math.sin(p*Math.PI*2)*.012*w}
export function poseHumanReader(h,amount=1){const t=clamp01(amount);h.body.position.y=lerp(0,-.49,t);h.body.rotation.x=lerp(0,.08,t);h.head.rotation.x=lerp(0,-.2,t);for(const l of[h.leftLeg,h.rightLeg]){l.upper.rotation.x=lerp(0,-1.24,t);l.lower.rotation.x=lerp(0,1.44,t);l.shoe.rotation.x=lerp(0,-.2,t)}h.leftArm.upper.rotation.x=h.rightArm.upper.rotation.x=lerp(0,-1.02,t);h.leftArm.fore.rotation.x=h.rightArm.fore.rotation.x=lerp(0,-1.08,t)}
export const poseSeatedReader=poseHumanReader;
